// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0-8BgOPc1tHnE_Jw4Ub2Orpzll9TWvI',
    appId: '1:105231643316:android:d952e25ac57bae8a1bdde1',
    messagingSenderId: '105231643316',
    projectId: 'flutternotes-48d58',
    storageBucket: 'flutternotes-48d58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYddxjl8cGnH43CJORGV2YZMlnp-1jUAc',
    appId: '1:105231643316:ios:f8b1e5b7f49f21e71bdde1',
    messagingSenderId: '105231643316',
    projectId: 'flutternotes-48d58',
    storageBucket: 'flutternotes-48d58.appspot.com',
    iosBundleId: 'com.example.task7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYddxjl8cGnH43CJORGV2YZMlnp-1jUAc',
    appId: '1:105231643316:ios:e31c87409183f30c1bdde1',
    messagingSenderId: '105231643316',
    projectId: 'flutternotes-48d58',
    storageBucket: 'flutternotes-48d58.appspot.com',
    iosBundleId: 'com.example.task7.RunnerTests',
  );
}
